# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42c16800eaee28b9cc037f72c53963082f1c5e0419a226fb87bc48f802e2a124be83eefa540c960c1588c7cc682a3cbf873d1d7b7e95f02751645bfc6a98323b

test:
  secret_key_base: fce0ac5129909691b0f29efee53016d1a8b186c969a97a73431ea23ef1747ad5af9b6a2bf2a1fa895052af3b5ffbea212182b9ae34a34c73dc7edfb997c1f34d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
